name: Deploy backend to Azure Web App (caloriepaws)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # หรือ 18 LTS ก็ได้

      - name: Install deps
        working-directory: backend
        run: npm ci

      - name: Build (optional)
        working-directory: backend
        run: npm run build --if-present

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: caloriepaws
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE_NODE }}
          package: backend
