name: deploy-caloriepaws

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  AZURE_WEBAPP_NAME: caloriepaws

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install
        working-directory: ./backend
        run: npm ci

      # ถ้าไม่มี script build จะข้ามอัตโนมัติ (ไม่ใช้ jq)
      - name: Build (if exists)
        working-directory: ./backend
        run: |
          if grep -q '"build"' package.json; then
            npm run build
          else
            echo "no build script; skipping"
          fi

      # Deploy ด้วย Publish Profile (ไม่ต้อง azure/login)
      - name: Deploy to Azure Web App (Publish Profile)
        uses: azure/webapps-deploy@v3
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./backend.zip
          enable-oryx-build: false

