name: deploy-helloworld

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install
        working-directory: ./helloworld
        run: npm install

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_HELLO }}
            package: ./helloworld
            enable-oryx-build: false

