name: Build and deploy Node.js app to Azure Web App - caloriepaws-node

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: caloriepaws-node   # ชื่อ Web App บน Azure
  APP_DIR: backend                      # โฟลเดอร์แอปของคุณ
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.APP_DIR }}/package-lock.json

      - name: Install & build (backend)
        working-directory: ${{ env.APP_DIR }}
        run: |
          npm ci
          npm run build --if-present
          npm test --if-present

      - name: Upload artifact (backend only)
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            ${{ env.APP_DIR }}/
            !${{ env.APP_DIR }}/node_modules/**

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: app

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          package: app
