# Docs: https://github.com/Azure/webapps-deploy

name: Build and deploy Node.js app to Azure Web App - caloriepaws-node

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: caloriepaws-node   # ชื่อ Web App บน Azure
  APP_DIR: backend                      # โฟลเดอร์แอป (มี package.json อยู่ที่นี่)
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ${{ env.APP_DIR }}/package-lock.json

      - name: Install & build (backend)
        working-directory: ${{ env.APP_DIR }}
        run: |
          npm ci
          npm run build --if-present
          # ไม่รัน test เพื่อเลี่ยง exit 1

      - name: Upload artifact (backend only)
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            ${{ env.APP_DIR }}/
            !${{ env.APP_DIR }}/node_modules/**

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          # ใช้ได้ถ้าคุณตั้ง secrets ชุด auto ของ Portal แล้ว
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_636629E366534A3DAB782C6747A7B829 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F3802C9718694D83804AFBFEF39A4B9C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DB7E795125AA4B2B827F6ED37609E717 }}
          # แนะนำระยะยาว: เปลี่ยนไปใช้ชื่อสั้นๆ เช่น AZURE_CLIENT_ID / TENANT_ID / SUBSCRIPTION_ID

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          package: app
